# Generated by Django 5.2.7 on 2025-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.URLField(blank=True),
        ),
    ]
